styria/rss/urls.py
from django.conf.urls import patterns, url, include
from rss.views import RssListInput
from rss.views import RssBasic
from rss.views import RssEntry
from rss.views import RssCategory
from dal import autocomplete
from rss.models import RssFeedBulk
from rss.views import AuthorAutocomplete

app_name = 'rss'
urlpatterns = [
	url(r'^author-ac$', autocomplete.Select2QuerySetView.as_view(model=RssFeedBulk),name='select2_fk'),
	url(r'^author-autocomplete$', AuthorAutocomplete.as_view(), name='author-autocomplete'),		
	url(r'^list-rss$', RssEntry.as_view()),
	url(r'^list-rss/category/(?P<category>[a-zA-Z]+)$', RssCategory.as_view(), name='rss-category'),
	url(r'^rec$', RssBasic.as_view()),
    url(r'^list$', RssListInput.as_view()),
]

styria/styria/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	
    url(r'^rss/', include('rss.urls')),
    url(r'^admin/', admin.site.urls),
]

styria/rss/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.utils import simplejson

class RssInput(models.Model):
	address = models.CharField(max_length=150)
	title = models.CharField(max_length=150)
	pub_date = models.DateTimeField('date published', default=timezone.now)
	
	def get_absolute_url(self):
		return reverse('rssinput_list', kwargs={'pk': self.pk})
	
	def __str__(self):
		return 'ID: '+str(self.id)+', NASLOV:'+self.title+', URL:'+self.address

class FeedManager(models.Manager):
	def all_categories(self):
		from django.db import connection
		cursor = connection.cursor()
		cursor.execute("""
			SELECT DISTINCT(category)
			FROM rss_rssfeedbulk
			""")
		result_list = []
		for row in cursor.fetchall():
			f = row[0]
			result_list.append(f)
		return result_list
	
	def all_authors(self):
		from django.db import connection
		cursor = connection.cursor()
		cursor.execute("""
			SELECT DISTINCT(author)
			FROM rss_rssfeedbulk
			""")
		result_list = []
		for row in cursor.fetchall():
			f = row[0]
			result_list.append(f)
		return result_list
		
class RssFeedBulk(models.Model):
	title = models.CharField(max_length=150)
	pub_date = models.DateTimeField('date published', default=timezone.now)
	href = models.CharField(max_length=350)
	author = models.CharField(max_length=150)
	img_src = models.CharField(max_length=350)
	category = models.CharField(max_length=150)
	#author_link_id = models.ForeignKey('Author', null=True)
	#slug = models.SlugField(max_length=50, unique=True, blank=True, null=True)
	objects = FeedManager()
	
	
	#def get_absolute_url(self):
	#	return reverse('rsscategory_list', kwargs={'category': self.category})
	
	def __str__(self):
		return 'id: %s title: %s date: %s link: %s author: %s img link: %s category %s ' % (self.id, self.title, self.pub_date, self.href, self.author, self.img_src, self.category)

class Author(models.Model):
	author_name = models.ForeignKey('rss.rssfeedbulk')

styria/rss/forms.py
from django import forms
from dal import autocomplete
#from django.core.urlresolvers import reverse
#from django.http import HttpResponseForbidden
#from django.views.generic import FormView
#from django.views.generic.detail import SingleObjectMixin

#from .models import RssInput

#class RssForm(forms.Form):

#class RssBasic(SingleObjectMixin, FormView):
from .models import RssInput, RssFeedBulk

class RssBasicForm(forms.Form):
    rss_address = forms.CharField(label='Rss address', max_length=255)
    rss_title = forms.CharField(label='Rss title', max_length=255)

class AuthorForm(forms.ModelForm):
	author = forms.ModelChoiceField(
	queryset=RssFeedBulk.objects.all_authors(),
	widget=autocomplete.ModelSelect2(url='author-autocomplete')
)
"""
class Meta:
	model = RssFeedBulk
	fields = ('__all__')
"""

styria/rss/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.views.generic import View, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import SingleObjectMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#from django.views.generic.edit import FormView
from dal import autocomplete


from .models import RssInput, RssFeedBulk
from .forms import RssBasicForm

class RssListInput(View):
	def get(self, request, *args, **kwargs):
		view = RssList.as_view()
		return view(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		view = RssBasic.as_view()
		return view(request, *args, **kwargs)

class RssList(ListView):
	model = RssInput	
	
	def get_context_data(self, **kwargs):
		context = super(RssList, self).get_context_data(**kwargs)
		form = RssBasicForm
		context['form'] = form
		return context
		
class RssDelete():
	model = RssInput

class RssBasic(FormView, SingleObjectMixin):
	template_name = 'rss/rssinput_list.html'
	form_class = RssBasicForm
	model = RssInput
	
	def post(self, request, *args, **kwargs):
		
		form = RssBasicForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			r = RssInput(address=cd['rss_address'],
						 title=cd['rss_title'])
			r.save()
			
			return HttpResponseRedirect('list')

class RssEntry(ListView):
	model = RssFeedBulk
	template_name = 'rss/rssfeedbulk_list.html'
	paginate_by = 20
	
	def get_context_data(self, **kwargs):
		context = super(RssEntry, self).get_context_data(**kwargs) 
		rssfeedbulk_list_earliest = RssFeedBulk.objects.order_by('-pub_date')
		paginator = Paginator(rssfeedbulk_list_earliest, self.paginate_by)

		page = self.request.GET.get('page')

		try:
			rssfeedbulk_list_earliest = paginator.page(page)
		except PageNotAnInteger:
			rssfeedbulk_list_earliest = paginator.page(1)
		except EmptyPage:
			rssfeedbulk_list_earliest = paginator.page(paginator.num_pages)

		context['rssfeedbulk_list_earliest'] = rssfeedbulk_list_earliest
		
		return context
		
class RssCategory(ListView):
	model = RssFeedBulk
	template_name = 'rss/rsscategory_list.html'
	paginate_by = 20
	
	def get_context_data(self, **kwargs):
		context = super(RssCategory, self).get_context_data(**kwargs)
		
		rss_category_list = RssFeedBulk.objects.filter(category=self.kwargs['category'])
		rss_all_categories = RssFeedBulk.objects.all_categories()
		
		paginator = Paginator(rss_category_list, self.paginate_by)

		page = self.request.GET.get('page')

		try:
			rss_category_list = paginator.page(page)
		except PageNotAnInteger:
			rss_category_list = paginator.page(1)
		except EmptyPage:
			rss_category_list = paginator.page(paginator.num_pages)
		
		context['rss_category_list'] = rss_category_list
		context['rss_all_categories'] = rss_all_categories
		
		return context
		
class AuthorAutocomplete(autocomplete.Select2QuerySetView):
	template_name = 'rss/authorcomplete.html'
	model = RssFeedBulk
	
	
	def get_context_data(self, **kwargs):
		search_qs = RssFeedBulk.objects.filter(author__startswith=request.REQUEST['search'])
		results = []
		for r in search_qs:
			results.append(r.author)
		resp = request.REQUEST['callback'] + '(' + simplejson.dumps(result) + ');'
		context['resp'] = resp
		
		return context
	"""
	def get_context_data(self, **kwargs):
		context = super(RssList, self).get_context_data(**kwargs)
		form = AuthorForm
		context['form'] = form
		return context
		
		
	
	"""	


"""	
def index(request):
    form = RssForm()
    rss_list = RssInput.objects.order_by('title')
    context = {'rss_list': rss_list, 'form': form}
    return render(request, 'rss/index.html', context)

def rss_save(request):
    if request.method == 'POST':
        form = RssForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            r = RssInput(address=cd['address'],
                         title=cd['title'])
            r.save()
            
            return HttpResponseRedirect('rss/index.html')
"""
    # if a GET (or any other method) we'll create a blank form
    #else:
    #    form = RssForm()

    #return render(request, 'name.html', {'form': form})

styria/rss/templates/rss/index.html
{% if rss_list %}
    <ul>
    {% for rss in rss_list %}
        <li><a href="{{ rss.address }}">{{ rss.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No rss are available.</p>
{% endif %}

<h1>Submit your data</h1>
<!--
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
-->

<form action="/rss/rssbasic.html" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Submit" />
</form>

styria/rss/templates/rss/rsscategory_list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'rss/style.css' %}" />
	{% if rss_all_categories %}
	<ul>
	{% for category in rss_all_categories %}
	{% url 'rss:rss-category' category as the_url %}
	<a href="{{ the_url }}"><li>{{ category }}</li></a>
	
	{% endfor %}
	</ul>
	{% endif %}
<div class="">

    <div class="">
		{% if rss_category_list %}
		{% for feed in rss_category_list %}
        <article class="" >
			<a href="{{ feed.href }}"><h1>{{ feed.title }}</h1></a>
			<figure>
				{% if feed.img_src %}
				<img src="{{ feed.img_src }}" />
				{% else %}
				<img src="http://icons.iconarchive.com/icons/guillendesign/variations-3/256/Default-Icon-icon.png" style="width:100px; height:66px;" />
				{% endif %}
				<figcaption>
					<p>Datum objave:</p>
					<time datetime="2016-06-01 00:00:00">{{ feed.pub_date }}</time>
					<p>Autor:</p>
					<span class="author">{{ feed.author }}</span>
				</figcaption>
			</figure>
		</article>
		{% endfor %}
		
		{% else %}
		<ul>
			<li>No feeds yet.</li>
		</ul>
		{% endif %}
	</div>
</div>

{% if is_paginated %}
  <nav>
    <ul class="pagination">
      {% if rss_category_list.has_previous %}
        <li>
          <a href="?page={{ rss_category_list.previous_page_number }}">
            <span>Previous</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#">
            <span>Previous</span>
          </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == rss_category_list.number %}class="active"{% endif %}>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
      {% endfor %}

      {% if rss_category_list.has_next %}
        <li>
          <a href="?page={{ rss_category_list.next_page_number }}">
            <span>Next</span>
          </a>
        </li>
      {% else %}
        <li {% if not rss_category_list.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

styria/rss/templates/rss/rssfeedbulk_list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'rss/style.css' %}" />	
<div class="">

    <div class="">
		{% if rssfeedbulk_list_earliest %}
		{% for feed in rssfeedbulk_list_earliest %}
        <article class="" >
			{% url 'rss:rss-category' feed.category as the_url %}
			<a href="{{ the_url }}"><h1>{{ feed.title }}</h1></a>
			<figure>
				{% if feed.img_src %}
				<img src="{{ feed.img_src }}" />
				{% else %}
				<img src="http://icons.iconarchive.com/icons/guillendesign/variations-3/256/Default-Icon-icon.png" style="width:100px; height:66px;" />
				{% endif %}
				<figcaption>
					<p>Datum objave:</p>
					<time datetime="2016-06-01 00:00:00">{{ feed.pub_date }}</time>
					<p>Autor:</p>
					<span class="author">{{ feed.author }}</span>
				</figcaption>
			</figure>
		</article>
		{% endfor %}
		
		{% else %}
		<ul>
			<li>No feeds yet.</li>
		</ul>
		{% endif %}
	</div>
</div>

{% if is_paginated %}
  <nav>
    <ul class="pagination">
      {% if rssfeedbulk_list_earliest.has_previous %}
        <li>
          <a href="?page={{ rssfeedbulk_list_earliest.previous_page_number }}">
            <span>Previous</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#">
            <span>Previous</span>
          </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == rssfeedbulk_list_earliest.number %}class="active"{% endif %}>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
      {% endfor %}

      {% if rssfeedbulk_list_earliest.has_next %}
        <li>
          <a href="?page={{ rssfeedbulk_list_earliest.next_page_number }}">
            <span>Next</span>
          </a>
        </li>
      {% else %}
        <li {% if not rssfeedbulk_list_earliest.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

styria/rss/templates/rss/rssinput_list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'rss/style.css' %}" />

{% if rssinput_list %}
    <ul>
    {% for rss in rssinput_list %}
        <li><a href="{{ rss.address }}">{{ rss.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No rss are available.</p>
{% endif %}

<h1>Submit your data</h1>
<!--
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
-->

<form action="/rss/rec" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Submit" />
</form>